nli_models:
  xlm-roberta-large-xnli:
    model_name: "xlm-roberta-large-xnli"
    model_path: "./nli_models/trt_models/nli_model_dynamic_bs.trt"
    tokenizer_path: "joeddav/xlm-roberta-large-xnli"

embedding_models:
  bge-m3:
    model_name: "bge-m3"
    model_path: "./embedding_models/trt_models/bge_m3_model_dynamic_bs.trt"
    tokenizer_path: "./embedding_models/bge-m3-tokenizer"

reranking_models:
  bge-reranker-large:
    model_name: "bge-reranker-large"
    model_path: "./reranker_models/trt_models/bge_reranker_large_dynamic_bs.trt"
    tokenizer_path: "./reranker_models/bge-reranker-large-tokenizer"


